### ISSUE TITLE
Example notebook failing on google colab

### ISSUE THREAD

**Issue by jchodera** [jaimergp/condacolab#5] opened 2021-03-17 15:50 UTC
I'm seeing the example notebook fail on google colab:
![image](https://user-images.githubusercontent.com/3656088/111496772-ce3ec480-86fd-11eb-85a2-5efed0202753.png)

**Comment by jaimergp** [comment] 2021-03-17 15:54
Hm, I've just run it and it works. What kind of environment are you using? I am using a GPU-enabled one.

Check here:

![image](https://user-images.githubusercontent.com/2559438/111497481-6dd17680-8741-11eb-816f-affb0e70bccd.png)


(sorry about the Spanish UI, no way to configure that...)(

**Comment by jaimergp** [comment] 2021-03-17 16:17
I've tried with several configurations and it always worked, so I can't reproduce that issue. Maybe try re-running in case it was a sporadic issue?

**Comment by jaimergp** [comment] 2021-03-17 17:52
My steps:

1. Open example notebook
2. Make sure we are using a GPU env
3. Execute first cell
4. Wait until the kernel automatically restarts
5. Run 2nd cell
6. Profit!


Here is a GIF in case it's easier to see than read!

![condacolab](https://user-images.githubusercontent.com/2559438/111514248-d7598100-8751-11eb-9fe5-95d4e6ebc657.gif)

**Comment by jchodera** [comment] 2021-03-18 03:14
Ah, it must be that you need to manually wait for the kernel to restart! If you click "Run all" from a clean instance, does it fail for you too?

**Comment by jaimergp** [comment] 2021-03-18 08:53
Ah, yeah, that's it! The 2nd cell will run before the kernel is restarted. However, that ends up happening and you can just run the 2nd cell once you get that notification in the bottom left corner. I'll add a note to the notebook!

**Comment by jaimergp** [comment] 2021-04-08 12:59
The example notebook has more disclaimers now, so closing this! Thanks for the report!

**Closed by jaimergp** 2021-04-08 12:59 UTC
